services:
  postgres:
    container_name: postgres-nimuairy
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userPassword
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: nimuairy
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - nimuairy
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-nimuairy
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  nimuairy:
    driver: bridge

volumes:
  postgres:
    driver: local