spring:
  application:
    -name: nimuairy-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/yaml
server:
  port: 8000
